export const environment = {
  servletPath: 'app',
  url: 'http://localhost:8080/api/apple-stationery',

  dashboard: 'dashboard',
  master: 'master',
  order: 'order',

  aosUser: 'aos-user',
  customerMaster: 'customer',
  dispatch: 'dispatch',
  stationeryDispatch: 'stationery-dispatch',
  dispatchDetails: 'dispatch-details',
  item: 'item',
  itemCategory: 'item-category',
  itemPrice: 'item-price',
  user: 'user',
  gstMaster: 'gst',
  file: 'file',
  courierMaster: 'courier',
  brandMaster: 'brand',
  orderMaster: 'order',
  poster: 'poster',
  courierDetails: 'courier-details',
  reports: 'reports',
  raiseTicket: 'ticket-status',

  list: 'list',
  create: 'create',
  view: 'view',
  edit: 'edit',
};
